# Trigger
- name: "content"
  color: "c2e0c6"
  description: "New content to process"

# Type
- name: "type:article"
  color: "c5def5"
  description: "Blog post, news, tech article"
- name: "type:slide"
  color: "c5def5"
  description: "Slides, presentation"
- name: "type:video"
  color: "c5def5"
  description: "YouTube, conference video"
- name: "type:book"
  color: "c5def5"
  description: "Book"
- name: "type:paper"
  color: "c5def5"
  description: "Academic paper"
- name: "type:podcast"
  color: "c5def5"
  description: "Podcast"
- name: "type:other"
  color: "c5def5"
  description: "Other"

# Topic
- name: "topic:ai"
  color: "dddddd"
  description: "AI, Machine Learning, LLM"
- name: "topic:backend"
  color: "dddddd"
  description: "Backend, API, Database"
- name: "topic:frontend"
  color: "dddddd"
  description: "Frontend, UI, CSS"
- name: "topic:infrastructure"
  color: "dddddd"
  description: "Infrastructure, DevOps, SRE"
- name: "topic:career"
  color: "dddddd"
  description: "Career, Work style"
- name: "topic:productivity"
  color: "dddddd"
  description: "Productivity, Tools"
